environment:
  nodejs_version: "24"
 
branches:
  only:
    - master  # ветка git
    - main

install:
  - npm install  # команда установки зависимостей

build: off  # отключаем встроенную в appveyor систему сборки

test_script:
  - npm run test  # скрипт тестирования
